### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by ChrisMcKee** [ulamlabs/rabbitmq-cluster#1]
Hi; out of curiosity; why do you run rabbit in a docker container within a single instance, within the autoscale group rather than directly on the machine?

**Comment by krotkiewicz** [comment]
Hello @ChrisMcKee, 2 reasons probably: 
- I have used rabbitmq docker image long before preparing this solution so I just felt more comfortable with it
- I was not even sure what kind of rabbitmq version is there in official yum repository for given linux distribution, with docker, you can pick and upgrade version without even thinking about underlying yum/apt repository.

Probably solution without docker would more "pure" but there was no time to prepare it.
