### ISSUE TITLE
Load Balancer not marking instances as healthy

### ISSUE THREAD

**Issue by johannes-schuetze** [ulamlabs/rabbitmq-cluster#11]
Script does not work out of the box. Auto scaling group keeps terminating RabbitMQ servers due to load balancer not marking instances as healthy. Since the health check is over port 5672 it suggests that RabbitMQ docker is either not configured right or not starting properly.

**Comment by rraub** [comment]
its been working for me, you might consider checking the system log on the ec2 instances to get a hint as to why they are not starting up. Maybe they don't have access to the internet to pull the docker image.
