### ISSUE TITLE
validation error during apply because of duplicate entries

### ISSUE THREAD

**Issue by schemert15** [ulamlabs/rabbitmq-cluster#12]
During apply I get this error:

2 error(s) occurred:

* aws_elb.elb: 1 error(s) occurred:

* aws_elb.elb: ValidationError: Either AvailabilityZones or SubnetIds must be specified
        status code: 400, request id: 550d8253-38dc-11e9-a881-d79abf3541d8
* aws_launch_configuration.rabbitmq: 1 error(s) occurred:

* aws_launch_configuration.rabbitmq: Error creating launch configuration: ValidationError: Must use either use group-id or group-name for all the security groups, not both at the same time
        status code: 400, request id: 5af9c704-38dc-11e9-9116-9de1e4d172ac

Which should be leading and how to fix this?

Thanks,
Sander

**Comment by BenCoughlan15** [comment]
change the name to name_prefix in the Launch configuration
