### ISSUE TITLE
Clustering does not work - Uppercase Hostnames

### ISSUE THREAD

**Issue by looney1** [ulamlabs/rabbitmq-cluster#2]
Thank you for this script!  I has saved us a considerable amount of time.  Unfortunately, running this unchanged presented a couple of challenges around clustering.  The rabbit nodes were unable to establish an erlang cluster.  

I was able to eventually get it to work by adding -e RABBITMQ_USE_LONGNAME=true to the docker run command, and setting to uppercase the hostnames.

I'll submit a pull request for your review around this issue.

**Comment by krotkiewicz** [comment]
Hello @looney1, I completely missed `RABBITMQ_USE_LONGNAME` option, please provide a PR and I will be happy to verify it and merge.

Thank you !

**Comment by warrenmcquinn** [comment]
Hey there, interested in using this script. Can you (@looney1) please explain a little more what you meant about setting the hostnames to uppercase?

Would a quick PR be possible? Thanks!

**Comment by krotkiewicz** [comment]
I added that parameter in newest version, please give it a try.
