### ISSUE TITLE
Ephemeral Storage upto 1TiB

### ISSUE THREAD

**Issue by rahulraju93** [ulamlabs/rabbitmq-cluster#6]
Is there a way to setup ephemeral storage in the scripts so that nodes have a higher storage capacity? Our RabbitMQ cluster crashes because of our production workloads. I was wondering if you considered the storage capacity here or could point me in the right direction? Please do the needful.

**Comment by krotkiewicz** [comment]
@rahulraju93 it is already done in new version, please give it a try !
