### ISSUE TITLE
Clustering does not work ***NOT WORKING CODE***

### ISSUE THREAD

**Issue by rahulraju93** [ulamlabs/rabbitmq-cluster#8]
Hello,
         I have attempted to use your code on AWS. I have been testing this for a week now without any progress. The nodes are configured individually and there is no HA or clustering occurring. The nodes individually have a RabbitMQ broker and the ELB directs traffic in a round robin fashion. The nodes do not mirror and there is no clustering. 

For example see below,

oot@ip-10-101-204-179:/# rabbitmqctl cluster_status
Cluster status of node rabbit@ip-10-101-204-179 ...
[{nodes,[{disc,['rabbit@ip-10-101-204-179']}]},
 {running_nodes,['rabbit@ip-10-101-204-179']},
 {cluster_name,<<"rabbit@ip-10-101-204-179">>},
 {partitions,[]},
 {alarms,[{'rabbit@ip-10-101-204-179',[]}]}]

Only ONE node is present in each cluster. Could you please fix this issue since there is no HA or clustering currently happening with the code. The problem is with the join_cluster.sh and find_hosts.sh scripts.

**Comment by leynebe** [comment]
The asg name change to name_prefix is what killed the cluster pairing. This was changed in commit "- autogenerate passwords and cookie secret".
Line 17 in cloud-init.yaml looks for the simple asg name, which now doesn't work anymore since it is now appended with a suffix.
