### ISSUE TITLE
Console is displaying "Management API returned status code 504"

### ISSUE THREAD

**Issue by jbidinger** [ulamlabs/rabbitmq-cluster#9]
Any idea where I should look. After connecting and logging into the rabbitmq console via the load balancer for 15-30 seconds "Management API returned status code 504 -" displays on the bottom of the screen. I am testing with t2.small. Too small maybe?

Version = "2.0.1".

**Comment by jbidinger** [comment]
After more digging. This isn't your issue.

**Comment by DmitryRibalka** [comment]
did someone solve this issue?

**Comment by DenisBY** [comment]
@jbidinger it would be nice to see your solution as we having the same issue
